/*var expressCode={"kdn":[
    {
        "com":"顺丰",
        "no":"SF"
    },
    {
        "com":"申通",
        "no":"STO"
    },
    {
        "com":"圆通",
        "no":"YTO"
    },
    {
        "com":"韵达",
        "no":"YD"
    },
    {
        "com":"天天",
        "no":"HHTT"
    },
    {
        "com":"EMS",
        "no":"EMS"
    },
    {
        "com":"中通",
        "no":"ZTO"
    },
    {
        "com":"汇通",
        "no":"HTKY"
    }
], "jh":[
    {
        "com":"顺丰",
        "no":"sf"
    },
    {
        "com":"申通",
        "no":"sto"
    },
    {
        "com":"圆通",
        "no":"yt"
    },
    {
        "com":"韵达",
        "no":"yd"
    },
    {
        "com":"天天",
        "no":"tt"
    },
    {
        "com":"EMS",
        "no":"ems"
    },
    {
        "com":"中通",
        "no":"zto"
    },
    {
        "com":"汇通",
        "no":"ht"
    }
]};*/


//kdnno快递鸟，jhno聚合数据，yz有赞商城
var expressCode=[
    {
        "com":"顺丰",
        "kdnno":"SF",
        "jhno":"sf",
        "yz":"7"
    },
    {
        "com":"申通",
        "kdnno":"STO",
        "jhno":"sto",
        "yz":"1"
    },
    {
        "com":"圆通",
        "kdnno":"YTO",
        "jhno":"yt",
        "yz":"2"
    },
    {
        "com":"韵达",
        "kdnno":"YD",
        "jhno":"yd",
        "yz":"4"
    },
    {
        "com":"天天",
        "kdnno":"HHTT",
        "jhno":"tt",
        "yz":"5"
    },
    {
        "com":"EMS",
        "kdnno":"EMS",
        "jhno":"ems",
        "yz":"11"
    },
    {
        "com":"中通",
        "kdnno":"ZTO",
        "jhno":"zto",
        "yz":"3"
    },
    {
        "com":"汇通",
        "kdnno":"HTKY",
        "jhno":"ht",
        "yz":"6"
    }
];

module.exports.expressCode = expressCode;